### ISSUE TITLE
Automated STIG Implementation for PX4 Autopilot

### ISSUE THREAD

**Issue by bpmooch** [render-se/PX4-Autopilot#5]
This ticket captures the implementation details requirements coming out the delivered Flight Controller STIG

[Internal spreadsheet view of PX4 STIG](https://renderse.sharepoint.com/:x:/s/Projects_SRA/EVx2lWss5BFCu8hhfTp9WaEBuy32MQgzkTLtMd353aJaMA?e=uifRZG)

[PX4 STIG Deliverable spreadsheet](https://renderse.sharepoint.com/:x:/s/Projects_SRA/ER7r75ZwrKhMjathBLsYuTUBF7DRwpBgWR3HYR3QqQiSew?e=D03bF2)

## PX4-Autopilot Acceptance Criteria
- [x] Manually copy the px4_sitl make target to determine differences between sitl and fmu-v5
- [x] #7
- [x] #9
- [ ] #10 
- [ ] Create px4_fmu-v5-constrained_test make target for running tests against stig compliant firmware build
- [ ] Run thread sanitizer on every test build ([reference issue](https://github.com/render-se/SRA/issues/14))
- [ ] Remove any XML code from firmware builds. First pass showed only `xmlrpc` lib which can be removed from nuttx-apps repo ([reference issue](https://github.com/render-se/SRA/issues/15))
- [ ] Remove nuttshell from PX4 build. It's possible nuttshell can't be fully disabled due to heavy usage in PX4-Autopilot ([reference issue](https://github.com/render-se/SRA/issues/11))

## "Turbotax" Acceptance Criteria
- [ ] We need to determine what "error handling vulnerabilities" are in a defensible way ([reference issue](https://github.com/render-se/SRA/issues/17))
- [ ] Generate software bill of materials ([reference link](https://www.cybersecuritydive.com/news/software-bill-of-materials-sbom-biden-executive-order-supply-chain/606846/))

**Comment by jrn90** [comment]
**Fun find**: Changing the `CMAKE_BUILD_TYPE` to anything but `Release` will break the **px4_fmu-v5** target from compiling (typically with a stack overflow `Wframe-larger-than` error). This is because the `Release` target by default injects two compiler flags for gcc: `-Os` and `-DNDEBUG`.

- `-Os` sets gcc's Optimize Options to optimize for size. [Ref](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html)
- `-DNDEBUG` disables all assert() functions. [Ref](https://en.cppreference.com/w/cpp/error/assert) and [Ref](https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html#Preprocessor-Options)

Appending these two compiler flags onto the px4_fmu-v5 target solves the issue of not being able to compile.
